// ⚡ THIS IS A GENERATED FILE FROM 'setupRoute.js' 
// ⚠️ DO NOT EDIT THIS FILE DIRECTLY EXCEPT YOU HAVE READ THE 'README.md' file 

import Landing from './pages/user/Landing';

export const landing = '/landing';

export default [
	{ path: landing, component: Landing}
];